---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cluster-ca.fullname" . }}-ca
  labels:
    {{- include "cluster-ca.labels" . | nindent 4 }}
spec:
  isCA: true
  secretName: {{ include "cluster-ca.fullname" . }}-ca
  commonName: {{ include "cluster-ca.fullname" . }}-ca
  usages:
    - client auth
    - server auth
  subject:
    organizations:
      - {{ .Values.caOrganization }}
  privateKey:
    rotatePolicy: Always
    algorithm: ECDSA
    size: 256
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "cluster-ca.fullname" . }}-ca-issuer
