---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cluster-ca.fullname" . }}
  labels:
    {{- include "cluster-ca.labels" . | nindent 4 }}
spec:
  isCA: true
  secretName: {{ include "cluster-ca.fullname" . }}
  commonName: {{ include "cluster-ca.fullname" . }}
  usages:
    {{- range $usage := .Values.ca.usages }}
    - {{ $usage }}
    {{- end }}
  subject:
    organizations:
      - {{ .Values.ca.organization }}
  privateKey:
    rotationPolicy: {{ .Values.ca.privateKeyRotationPolicy }}
    algorithm: ECDSA
    size: 256
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "cluster-ca.fullname" . }}-issuer
