---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cluster-ca.fullname" . }}-ca
  labels:
    {{- include "cluster-ca.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "cluster-ca.fullname" . }}-ca
