---
name: Lint and Test
on: push

jobs:
  main:
    name: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: helm/chart-testing-action@v2.2.1
      - run: ct lint --chart-dirs . --charts cluster-ca
      - uses: helm/kind-action@v1
      - run: ct install --chart-dirs . --charts cluster-ca
